export const TokenList = [
  {
    tokenName: 'bnbp',
    tokenImg: 'bnbp',
    tokenColor: '#d6a31f',
    decimal: 18,
    tax: null,
    burn: 12.5,
    stakers: 12.5,
    fee: null,
    marketing: null,
    videoTime: 10,
  },
  {
    tokenName: 'volt',
    tokenImg: 'vo',
    tokenColor: '#ccda50',
    decimal: 9,
    tax: 0,
    stakers: null,
    burn: 7.5,
    fee: 7.5,
    marketing: 10,
    videoTime: 10,
  },
  {
    tokenName: 'sgo',
    tokenImg: 'sgo',
    tokenColor: '#0b890b',
    secondaryColor: '#b76931',
    shadowColor: '#047e27',
    tax: 0,
    burn: 10,
    fee: 10,
    treasury: 10,
    videoTime: 8,
    usdDecimal: 6,
    decimal: 18,
  },
];

export const ComingToken = {
  tokenName: 'volt',
  tokenImg: 'vo',
  tokenColor: '#ccda50',
  decimal: 9,
};
