import { makeStyles } from '@material-ui/core';

export const useStyles = makeStyles((theme) => ({
  root: { display: 'flex', flexDirection: 'column' },
  line: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 20px',
  },
  input: {
    background: `#e8e8e800!important`,
    border: 0,
    color: `grey`,
    fontSize: `30px`,
    margin: `0 5px`,
    maxWidth: `150px`,
    minHeight: `30px`,
    outline: `none`,
    padding: `0 5px`,
    textAlign: `left`,
  },
  tokenSelDiv: {},
  maxSpan: {
    border: `0.5px solid #f3ba2c`,
    borderRadius: `6px`,
    color: `#f3ba2c`,
    display: `inline-block`,
    fontSize: `8px`,
    marginLeft: `-50px`,
    marginRight: `10px`,
    marginTop: `5px`,
    maxHeight: `10px`,
    minHeight: `10px`,
    padding: `4px`,
    position: `absolute`,
    textAlign: `center`,
    textTransform: `uppercase`,
    width: `31px`,
    cursor: 'pointer',
  },
  tokenBtn: {
    background: '#232a4a',
    boxShadow: '2px 2px 2px #161a2f, inset 2px 2px #495a8d',
    alignItems: `center`,
    borderRadius: `15px`,
    display: `flex`,
    justifyContent: `space-evenly`,
    padding: `8px`,
    width: `90px`,
    color: theme.palette.project.font,
    fontSize: '0.9rem',
    cursor: 'pointer',
    border: '1px solid transparent',
    transition: 'all 0.2s linear',
    '&:hover': {
      boxShadow: `0px 0px 4px #3f3e3e`,
      border: `1px solid #737373`,
    },
    '& img': {
      width: '15px',
      height: '15px',
    },
  },
  usdValue: {
    color: theme.palette.project.font,
    fontSize: '0.9rem',
    paddingLeft: '10px',
  },
  balance: {
    color: theme.palette.project.font,
    fontSize: '0.75rem',
    paddingLeft: '10px',
  },
  potcontract: {
    display: `flex`,
    justifyItems: `center`,
    marginTop: `2px`,
  },
  qrcode: {
    '& img': {
      width: `120px`,
      padding: `10px 30px`,
      [theme.breakpoints.down('xs')]: {
        padding: '10px',
      },
    },
  },
  addressDiv: {
    padding: `5px`,
    paddingLeft: `0px`,
    color: theme.palette.project.font,
    [theme.breakpoints.down('sm')]: {
      padding: `30px 0px`,
    },
  },
  copyImg: {
    border: `1px solid #484b65`,
    display: `inline-flex`,
    alignItems: `flex-end`,
    marginTop: `5px`,
    borderRadius: `5px`,
    marginBottom: `5px`,
  },
  address: {
    fontSize: `11px`,
    height: `20px`,
    padding: `0px 0px 0px 10px`,
  },
}));
